[2024-08-11T08:38:07.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T08:38:07.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-08-11T08:38:07.609+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-08-11T08:38:07.609+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-11T08:38:07.624+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_to_s3_bucket_zillowapibucket> on 2024-08-10 00:00:00+00:00
[2024-08-11T08:38:07.628+0000] {standard_task_runner.py:64} INFO - Started process 3557 to run task
[2024-08-11T08:38:07.629+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Analytics_DAG', 'load_to_s3_bucket_zillowapibucket', 'scheduled__2024-08-10T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/zillowrapidapi.py', '--cfg-path', '/tmp/tmp2qtj2hcj']
[2024-08-11T08:38:07.631+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_to_s3_bucket_zillowapibucket
[2024-08-11T08:38:07.668+0000] {task_command.py:426} INFO - Running <TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [running]> on host ip-172-31-11-55.ap-south-1.compute.internal
[2024-08-11T08:38:07.735+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vkkr800@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Analytics_DAG' AIRFLOW_CTX_TASK_ID='load_to_s3_bucket_zillowapibucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-10T00:00:00+00:00'
[2024-08-11T08:38:07.736+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T08:38:07.747+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-11T08:38:07.747+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_11082024083801.json s3://zillow-api-bucket-1st/']
[2024-08-11T08:38:07.753+0000] {subprocess.py:86} INFO - Output:
[2024-08-11T08:38:08.192+0000] {subprocess.py:93} INFO - move failed: ../../home/ubuntu/response_data_11082024083801.json to s3://zillow-api-bucket-1st/response_data_11082024083801.json Unable to locate credentials
[2024-08-11T08:38:08.256+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-08-11T08:38:08.256+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T08:38:08.263+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-11T08:38:08.265+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Zillow_Analytics_DAG, task_id=load_to_s3_bucket_zillowapibucket, run_id=scheduled__2024-08-10T00:00:00+00:00, execution_date=20240810T000000, start_date=20240811T083807, end_date=20240811T083808
[2024-08-11T08:38:08.282+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task load_to_s3_bucket_zillowapibucket (Bash command failed. The command returned a non-zero exit code 1.; 3557)
[2024-08-11T08:38:08.326+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-11T08:38:08.336+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-11T08:38:08.336+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-11T13:32:50.237+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T13:32:50.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-08-11T13:32:50.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-08-11T13:32:50.256+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-11T13:32:50.272+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_to_s3_bucket_zillowapibucket> on 2024-08-10 00:00:00+00:00
[2024-08-11T13:32:50.276+0000] {standard_task_runner.py:64} INFO - Started process 6944 to run task
[2024-08-11T13:32:50.278+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Analytics_DAG', 'load_to_s3_bucket_zillowapibucket', 'scheduled__2024-08-10T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/zillowrapidapi.py', '--cfg-path', '/tmp/tmpctfc_uns']
[2024-08-11T13:32:50.279+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask load_to_s3_bucket_zillowapibucket
[2024-08-11T13:32:50.322+0000] {task_command.py:426} INFO - Running <TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [running]> on host ip-172-31-11-55.ap-south-1.compute.internal
[2024-08-11T13:32:50.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vkkr800@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Analytics_DAG' AIRFLOW_CTX_TASK_ID='load_to_s3_bucket_zillowapibucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-10T00:00:00+00:00'
[2024-08-11T13:32:50.394+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T13:32:50.405+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-11T13:32:50.406+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_11082024133242.json s3://zillow-api-bucket-1st/']
[2024-08-11T13:32:50.413+0000] {subprocess.py:86} INFO - Output:
[2024-08-11T13:32:51.045+0000] {subprocess.py:93} INFO - Completed 55.3 KiB/55.3 KiB (304.7 KiB/s) with 1 file(s) remainingmove: ../../home/ubuntu/response_data_11082024133242.json to s3://zillow-api-bucket-1st/response_data_11082024133242.json
[2024-08-11T13:32:51.124+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-11T13:32:51.124+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T13:32:51.144+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Zillow_Analytics_DAG, task_id=load_to_s3_bucket_zillowapibucket, run_id=scheduled__2024-08-10T00:00:00+00:00, execution_date=20240810T000000, start_date=20240811T133250, end_date=20240811T133251
[2024-08-11T13:32:51.175+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-11T13:32:51.189+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-11T13:32:51.197+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-11T13:35:07.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T13:35:07.373+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-08-11T13:35:07.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [queued]>
[2024-08-11T13:35:07.378+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-11T13:35:07.394+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_to_s3_bucket_zillowapibucket> on 2024-08-10 00:00:00+00:00
[2024-08-11T13:35:07.397+0000] {standard_task_runner.py:64} INFO - Started process 6972 to run task
[2024-08-11T13:35:07.400+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Analytics_DAG', 'load_to_s3_bucket_zillowapibucket', 'scheduled__2024-08-10T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/zillowrapidapi.py', '--cfg-path', '/tmp/tmpp1fuzxxp']
[2024-08-11T13:35:07.402+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask load_to_s3_bucket_zillowapibucket
[2024-08-11T13:35:07.440+0000] {task_command.py:426} INFO - Running <TaskInstance: Zillow_Analytics_DAG.load_to_s3_bucket_zillowapibucket scheduled__2024-08-10T00:00:00+00:00 [running]> on host ip-172-31-11-55.ap-south-1.compute.internal
[2024-08-11T13:35:07.509+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vkkr800@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Analytics_DAG' AIRFLOW_CTX_TASK_ID='load_to_s3_bucket_zillowapibucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-10T00:00:00+00:00'
[2024-08-11T13:35:07.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T13:35:07.520+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-11T13:35:07.520+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_11082024133501.json s3://zillow-api-bucket-1st/']
[2024-08-11T13:35:07.528+0000] {subprocess.py:86} INFO - Output:
[2024-08-11T13:35:08.124+0000] {subprocess.py:93} INFO - Completed 57.2 KiB/57.2 KiB (340.2 KiB/s) with 1 file(s) remainingmove: ../../home/ubuntu/response_data_11082024133501.json to s3://zillow-api-bucket-1st/response_data_11082024133501.json
[2024-08-11T13:35:08.198+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-11T13:35:08.198+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T13:35:08.217+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Zillow_Analytics_DAG, task_id=load_to_s3_bucket_zillowapibucket, run_id=scheduled__2024-08-10T00:00:00+00:00, execution_date=20240810T000000, start_date=20240811T133507, end_date=20240811T133508
[2024-08-11T13:35:08.256+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-11T13:35:08.269+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-11T13:35:08.279+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
