[2024-08-11T13:42:03.720+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T13:42:03.729+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T13:41:56.457182+00:00 [queued]>
[2024-08-11T13:42:03.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T13:41:56.457182+00:00 [queued]>
[2024-08-11T13:42:03.734+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-11T13:42:03.752+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): is_file_in_s3> on 2024-08-11 13:41:56.457182+00:00
[2024-08-11T13:42:03.755+0000] {standard_task_runner.py:64} INFO - Started process 7039 to run task
[2024-08-11T13:42:03.757+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Analytics_DAG', 'is_file_in_s3', 'manual__2024-08-11T13:41:56.457182+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/zillowrapidapi.py', '--cfg-path', '/tmp/tmplq5ib0my']
[2024-08-11T13:42:03.758+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask is_file_in_s3
[2024-08-11T13:42:03.794+0000] {task_command.py:426} INFO - Running <TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T13:41:56.457182+00:00 [running]> on host ip-172-31-11-55.ap-south-1.compute.internal
[2024-08-11T13:42:03.868+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vkkr800@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Analytics_DAG' AIRFLOW_CTX_TASK_ID='is_file_in_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T13:41:56.457182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-11T13:41:56.457182+00:00'
[2024-08-11T13:42:03.869+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T13:42:03.878+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-11T13:42:03.878+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:03.884+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-08-11T13:42:03.884+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-11T13:42:09.210+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:14.222+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:19.231+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:24.240+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:29.249+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:34.257+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:39.267+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:44.276+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:49.286+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:54.296+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:42:59.303+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:43:04.311+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket/response_data_11082024134158.csv
[2024-08-11T13:43:04.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T13:43:04.320+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 189, in execute
    super().execute(context)
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.44201697899916 seconds exceeds the specified timeout of 60.0.
[2024-08-11T13:43:04.324+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=Zillow_Analytics_DAG, task_id=is_file_in_s3, run_id=manual__2024-08-11T13:41:56.457182+00:00, execution_date=20240811T134156, start_date=20240811T134203, end_date=20240811T134304
[2024-08-11T13:43:04.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task is_file_in_s3 (Sensor has timed out; run duration of 60.44201697899916 seconds exceeds the specified timeout of 60.0.; 7039)
[2024-08-11T13:43:04.373+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-11T13:43:04.381+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-11T13:43:04.381+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
