[2024-08-11T13:07:07.090+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T13:07:07.100+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T13:06:58.095158+00:00 [queued]>
[2024-08-11T13:07:07.104+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T13:06:58.095158+00:00 [queued]>
[2024-08-11T13:07:07.104+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-11T13:07:07.119+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): is_file_in_s3> on 2024-08-11 13:06:58.095158+00:00
[2024-08-11T13:07:07.122+0000] {standard_task_runner.py:64} INFO - Started process 6279 to run task
[2024-08-11T13:07:07.124+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Analytics_DAG', 'is_file_in_s3', 'manual__2024-08-11T13:06:58.095158+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/zillowrapidapi.py', '--cfg-path', '/tmp/tmpmbn8bruf']
[2024-08-11T13:07:07.126+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask is_file_in_s3
[2024-08-11T13:07:07.161+0000] {task_command.py:426} INFO - Running <TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T13:06:58.095158+00:00 [running]> on host ip-172-31-11-55.ap-south-1.compute.internal
[2024-08-11T13:07:07.238+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vkkr800@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Analytics_DAG' AIRFLOW_CTX_TASK_ID='is_file_in_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T13:06:58.095158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-11T13:06:58.095158+00:00'
[2024-08-11T13:07:07.238+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T13:07:07.248+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-11T13:07:07.249+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:07.254+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-08-11T13:07:07.255+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-11T13:07:12.596+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:17.606+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:22.614+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:27.624+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:32.634+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:37.642+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:42.649+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:47.658+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:52.668+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:07:57.676+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:08:02.685+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:08:07.694+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024130700.json
[2024-08-11T13:08:07.702+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T13:08:07.703+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 189, in execute
    super().execute(context)
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.4537941109993 seconds exceeds the specified timeout of 60.0.
[2024-08-11T13:08:07.706+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=Zillow_Analytics_DAG, task_id=is_file_in_s3, run_id=manual__2024-08-11T13:06:58.095158+00:00, execution_date=20240811T130658, start_date=20240811T130707, end_date=20240811T130807
[2024-08-11T13:08:07.719+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 71 for task is_file_in_s3 (Sensor has timed out; run duration of 60.4537941109993 seconds exceeds the specified timeout of 60.0.; 6279)
[2024-08-11T13:08:07.755+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-11T13:08:07.762+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-11T13:08:07.762+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
