[2024-08-11T12:37:47.898+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T12:37:47.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T12:37:38.872433+00:00 [queued]>
[2024-08-11T12:37:47.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T12:37:38.872433+00:00 [queued]>
[2024-08-11T12:37:47.914+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-08-11T12:37:47.930+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): is_file_in_s3> on 2024-08-11 12:37:38.872433+00:00
[2024-08-11T12:37:47.934+0000] {standard_task_runner.py:64} INFO - Started process 6121 to run task
[2024-08-11T12:37:47.937+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Analytics_DAG', 'is_file_in_s3', 'manual__2024-08-11T12:37:38.872433+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/zillowrapidapi.py', '--cfg-path', '/tmp/tmpbzh6tvz1']
[2024-08-11T12:37:47.938+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask is_file_in_s3
[2024-08-11T12:37:47.973+0000] {task_command.py:426} INFO - Running <TaskInstance: Zillow_Analytics_DAG.is_file_in_s3 manual__2024-08-11T12:37:38.872433+00:00 [running]> on host ip-172-31-11-55.ap-south-1.compute.internal
[2024-08-11T12:37:48.044+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='vkkr800@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Analytics_DAG' AIRFLOW_CTX_TASK_ID='is_file_in_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T12:37:38.872433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-11T12:37:38.872433+00:00'
[2024-08-11T12:37:48.045+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T12:37:48.055+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-11T12:37:48.055+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:37:48.062+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-08-11T12:37:48.062+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-11T12:37:53.397+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:37:58.407+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:03.415+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:08.423+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:13.433+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:18.442+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:23.451+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:28.460+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:33.469+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:38.478+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:43.486+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:48.495+0000] {s3.py:118} INFO - Poking for key : s3://zillow-api-third-bucket//home/ubuntu/response_data_11082024123741.json
[2024-08-11T12:38:48.503+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T12:38:48.504+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 189, in execute
    super().execute(context)
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.4480275829992 seconds exceeds the specified timeout of 60.0.
[2024-08-11T12:38:48.507+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=Zillow_Analytics_DAG, task_id=is_file_in_s3, run_id=manual__2024-08-11T12:37:38.872433+00:00, execution_date=20240811T123738, start_date=20240811T123747, end_date=20240811T123848
[2024-08-11T12:38:48.522+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task is_file_in_s3 (Sensor has timed out; run duration of 60.4480275829992 seconds exceeds the specified timeout of 60.0.; 6121)
[2024-08-11T12:38:48.560+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-11T12:38:48.568+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-11T12:38:48.569+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
